Fix Flask with ROOT 5 issue
Produced an error with the output:
"
  File "/opt/root/lib/ROOT.py", line 215, in __getattr__
    klass = _root.MakeRootClass( attr, cls  )
TypeError: requested class 'ROOT::__file__' does not exist
"